src/django_file_inbox/urls.py
from django.urls import path

from django_file_inbox.views import Inbox, InboxMail

app_name = "django_file_inbox"

urlpatterns = [
    path("<str:filename>", InboxMail.as_view(), name="file_inbox_mail"),
    path("", Inbox.as_view(), name="file_inbox"),
]

src/django_file_inbox/views.py
import os
import re
import typing
from datetime import datetime
from pathlib import Path
from typing import Any

from django.conf import settings
from django.http import HttpResponse
from django.views.generic import ListView, TemplateView

if typing.TYPE_CHECKING:
    _Base = TemplateView
else:
    _Base = object


BASE_TEMPLATE = getattr(settings, "FILE_INBOX_BASE_TEMPLATE", "base.html")
BASE_TEMPLATE_BLOCK = getattr(settings, "FILE_INBOX_BLOCK", "content")


class BlockTemplatePreprocessorView(_Base):
    template_base_name: str

    def render_to_response(self, context: dict[str, Any], **response_kwargs: Any) -> HttpResponse:
        base_template_dir = Path(__file__).resolve().parent
        template = base_template_dir / "templates" / self.template_base_name
        replacements = {
            "block": r"""\{\%\s+(customblock)\s+(.*)\s+\%\}""",
            "endblock": r"""\{\%\s+(endcustomblock)\s+(.*)\s+\%\}""",
        }

        preprocessed_template = base_template_dir / "templates" / self.get_template_names()[0]
        with Path.open(preprocessed_template, mode="w") as new_template:
            with Path.open(template) as old_template:
                contents = old_template.read()
                for tagname, re_str in replacements.items():
                    contents = re.sub(re_str, f"{{% {tagname} {BASE_TEMPLATE_BLOCK} %}}", contents)

            new_template.write(contents)
            new_template.seek(0)

        return super().render_to_response(context, **response_kwargs)


class Inbox(BlockTemplatePreprocessorView, ListView):
    """
    Displays list of mails in file-based EmailBackend inbox
    """

    template_base_name = "django_file_inbox/inbox_template.html"
    template_name = "django_file_inbox/processed/inbox.html"

    context_object_name = "mail_list"
    paginate_by = getattr(settings, "FILE_INBOX_PAGINATION", 10)

    @staticmethod
    def _table_classes() -> str:
        if hasattr(settings, "FILE_INBOX_TABLE_CLASSES"):
            return settings.FILE_INBOX_TABLE_CLASSES

        if hasattr(settings, "FILE_INBOX_BOOTSTRAP"):
            return "table table-striped table-bordered table-hover"

        return ""

    @staticmethod
    def _table_style() -> str:
        return "table-layout: fixed; width: 100%; border-collapse: collapse;"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        classes = self._table_classes()
        context["file_inbox_table_classes"] = classes
        context["file_inbox_table_style"] = self._table_style() if not classes else ""
        context["file_inbox_base_template"] = BASE_TEMPLATE
        return context

    def get_queryset(self):  # noqa: PLR6301
        path = settings.EMAIL_FILE_PATH
        mail_list = os.listdir(path)
        mail_list.sort(reverse=True)
        mail_list = [{"filename": filename} for filename in mail_list if filename != ".gitkeep"]
        for mail in mail_list:
            subject = mail_from = mail_to = ts = False
            email_contents = (settings.EMAIL_FILE_PATH / mail["filename"]).read_text()
            for line in email_contents:
                if line.startswith("Subject:"):
                    subject = True
                    mail["subject"] = line[8:].strip()
                if line.startswith("From: "):
                    mail_from = True
                    mail["from"] = line[6:].strip()
                if line.startswith("To: "):
                    mail_to = True
                    mail["to"] = line[4:].strip()
                if line.startswith("Date: "):
                    ts = True
                    mail["timestamp"] = line[6:].strip()

                if subject and mail_from and mail_to and ts:
                    break

        return mail_list


class InboxMail(BlockTemplatePreprocessorView, TemplateView):
    """
    Displays specific mail from the file-based EmailBackend inbox
    """

    template_base_name = "django_file_inbox/inbox_email_template.html"
    template_name = "django_file_inbox/processed/inbox_email.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        filename = context["filename"]
        date_time = " ".join(Path(filename).stem.split("-")[:2])

        context["timestamp"] = datetime.strptime(date_time, "%Y%m%d %H%M%S").astimezone()

        filepath = settings.EMAIL_FILE_PATH / filename
        context["email_content"] = filepath.read_text()

        context["subject"] = ""
        for line in context["email_content"].split("\n"):
            if line.startswith("Subject:"):
                context["subject"] = line[8:].strip()
                break

        context["file_inbox_base_template"] = BASE_TEMPLATE
        return context

src/django_file_inbox/templates/django_file_inbox/_pagination.html
{% load i18n %}

{% if page_obj.paginator.num_pages > 1 %}
<nav aria-label="pagination" style="display: flex; justify-content: center; border-top: 1px solid #eee; margin-top: 1em; padding-top: 0.5em;">
    <ul class="pagination" style="list-style: none; display: flex">

        {# Go to first page if we're not on it #}
        {% if page_obj.number > 1 %}
            <li class="page-item" style="margin: 0 1px; padding: 1px 2px; justify-content: center;">
                <a 
                    class="page-link" href="?page=1" aria-label="{% translate 'First' %}"
                    style="display: block; padding: 0.5em 1em; border: 1px solid #999; border-radius: 0.2em; text-decoration: none;"
                >
                    <span>&laquo</span>
                </a>
            </li>
        {% endif %}
 
        {# Go to previous page if we're not on the first one #}
        {% if page_obj.has_previous %}
            <li class="page-item" style="margin: 0 1px; padding: 1px 2px; justify-content: center;">
                <a 
                    class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="{% translate 'Previous' %}"
                    style="display: block; padding: 0.5em 1em; border: 1px solid #999; border-radius: 0.2em; text-decoration: none;"
                >
                    <span>&lt</span>
                </a>
            </li>
        {% endif %}
 
        {# Go back 2 pages if we're on page number >= 2 #}       
        {% if page_obj.number > 2 %}
            <li class="page-item" style="margin: 0 1px; padding: 1px 2px; justify-content: center;">
                <a 
                    class="page-link" href="?page={{ page_obj.number|add:-2 }}" aria-label="{% translate 'Page' %} {{ page_obj.number|add:-2 }}"
                    style="display: block; padding: 0.5em 1em; border: 1px solid #999; border-radius: 0.2em; text-decoration: none;"
                >
                    <span aria-hidden="true">{{ page_obj.number|add:-2 }}</span>
                </a>
            </li>
        {% endif %}

        {# Go to previous page by page number if there is one #}
        {% if page_obj.has_previous %}
            <li class="page-item" style="margin: 0 1px; padding: 1px 2px; justify-content: center;">
                <a 
                    class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="{% translate 'Page' %} {{ page_obj.previous_page_number }}"
                    style="display: block; padding: 0.5em 1em; border: 1px solid #999; border-radius: 0.2em; text-decoration: none;"
                >
                    <span aria-hidden="true">{{ page_obj.previous_page_number }}</span>
                </a>
            </li>
        {% endif %}

        {# Current page - no link #}
        <li class="page-item" style="margin: 0 1px; padding: 1px 2px; justify-content: center;">
            <span style="display: block; background-color: lightgray; padding: 0.5em 1em; border: 1px solid #999; border-radius: 0.2em; text-decoration: none;">
                {{ page_obj.number }}
            </span>
        </li>

        {# Go to next page by page number if there is one #}
        {% if page_obj.has_next %}
            <li class="page-item" style="margin: 0 1px; padding: 1px 2px; justify-content: center;">
                <a 
                    class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="{% translate 'Next' %}"
                    style="display: block; padding: 0.5em 1em; border: 1px solid #999; border-radius: 0.2em; text-decoration: none;"
                >
                    <span aria-hidden="true">{{ page_obj.next_page_number }}</span>
                </a>
            </li>
        {% endif %}

        {# Go forward 2 pages if possible #}
        {% if page_obj.number < page_obj.paginator.num_pages|add:-1 %}
            <li class="page-item" style="margin: 0 1px; padding: 1px 2px; justify-content: center;">
                <a 
                    class="page-link" href="?page={{ page_obj.number|add:2 }}" aria-label="{% translate 'Page' %} {{ page_obj.number|add:2 }}"
                    style="display: block; padding: 0.5em 1em; border: 1px solid #999; border-radius: 0.2em; text-decoration: none;"
                >
                    <span aria-hidden="true">{{ page_obj.number|add:2 }}</span>
                </a>
            </li>
        {% endif %}

        {# Go to next page if we're not on the last one #}
        {% if page_obj.has_next %}
            <li class="page-item" style="margin: 0 1px; padding: 1px 2px; justify-content: center;">
                <a 
                    class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="{% translate 'Next' %}"
                    style="display: block; padding: 0.5em 1em; border: 1px solid #999; border-radius: 0.2em; text-decoration: none;"
                >
                    <span>&gt</span>
                </a>
            </li>
        {% endif %}

        {# Go to last page if we're not on it #}
        {% if page_obj.number < page_obj.paginator.num_pages %}
            <li class="page-item" style="margin: 0 1px; padding: 1px 2px; justify-content: center;">
                <a 
                    class="page-link" href="?page={{ page_obj.paginator.num_pages }}" aria-label="{% translate 'Last' %}"
                    style="display: block; padding: 0.5em 1em; border: 1px solid #999; border-radius: 0.2em; text-decoration: none;"
                >
                    <span aria-hidden="true">&raquo</span>
                </a>
            </li>
        {% endif %}
    </ul>
</nav>
{% endif %}

src/django_file_inbox/templates/django_file_inbox/inbox_email_template.html
{% extends file_inbox_base_template %}
{% load custom_block %}
{% load i18n %}

{% customblock inbox_extends %}
<br/>
<div style="margin: 0 auto; padding: 10px; border: 1px solid #EF9A9A; border-radius: 4px; overflow: hidden; display: flex; flex-direction: column; width: 75vw;">
    <h3>{{ filename }}</h3>
    <span><hr /></span>
    <span><strong>Subject: </strong>{{ subject }}</span>
    <small>{{ timestamp }}</small>
    <span><hr /></span>
    {{ email_content|linebreaks }}
</div>
{% endcustomblock main_content %}

src/django_file_inbox/templates/django_file_inbox/inbox_template.html
{% extends file_inbox_base_template %}
{% load custom_block %}
{% load i18n %}

{% customblock file_inbox_block_name %}
<h1>Inbox</h1>
{% block inbox_pagination_top %}
{% include 'django_file_inbox/_pagination.html' %}
{% endblock inbox_pagination_top %}
<table class="{{ file_inbox_table_classes }}" style="{{ file_inbox_table_style }}">
    <thead>
        <tr>
            <th scope="col" style="border-bottom: 2px solid black; text-align: left; padding: 0.1em 0.3em;"">{% translate "Email file" %}</th>
            <th scope="col" style="border-bottom: 2px solid black; text-align: left; padding: 0.1em 0.3em;">{% translate "Timestamp" %}</th>
            <th scope="col" style="border-bottom: 2px solid black; text-align: left; padding: 0.1em 0.3em;">{% translate "Subject" %}</th>
            <th scope="col" style="border-bottom: 2px solid black; text-align: left; padding: 0.1em 0.3em;">{% translate "From" %}</th>
            <th scope="col" style="border-bottom: 2px solid black; text-align: left; padding: 0.1em 0.3em;">{% translate "To" %}</th>
        </tr>
    </thead>
    <tbody>
    {% for email in mail_list %}
        <tr 
            {% if forloop.counter|divisibleby:2 %}style="background-color: lightgray"{% endif %}
            onclick="window.location='{% url "django_file_inbox:file_inbox_mail" filename=email.filename %}'"
        >
            <td scope="row" style="text-align: left; padding: 0.1em 0.3em;">{{ email.filename }}</td>
            <td style="text-align: left; padding: 0.1em 0.3em;"> {{ email.timestamp }}</td>
            <td style="text-align: left; padding: 0.1em 0.3em;"> {{ email.subject }}</td>
            <td style="text-align: left; padding: 0.1em 0.3em;"> {{ email.from }}</td>
            <td style="text-align: left; padding: 0.1em 0.3em;"> {{ email.to }}</td>
        </tr>
    {% empty %}
    <tr>
        <td class="text-center">{% translate "No messages found" %}</td>
    </tr>
    {% endfor %}
    </tbody>
</table>
{% block inbox_pagination_bottom %}
{% include 'django_file_inbox/_pagination.html' %}
{% endblock inbox_pagination_bottom %}

{% endcustomblock file_inbox_block_name %}

src/django_file_inbox/templates/django_file_inbox/processed/inbox.html
{% extends file_inbox_base_template %}
{% load custom_block %}
{% load i18n %}

{% block main_block %}
<h1>Inbox</h1>
{% block inbox_pagination_top %}
{% include 'django_file_inbox/_pagination.html' %}
{% endblock inbox_pagination_top %}
<table class="{{ file_inbox_table_classes }}" style="{{ file_inbox_table_style }}">
    <thead>
        <tr>
            <th scope="col" style="border-bottom: 2px solid black; text-align: left; padding: 0.1em 0.3em;"">{% translate "Email file" %}</th>
            <th scope="col" style="border-bottom: 2px solid black; text-align: left; padding: 0.1em 0.3em;">{% translate "Timestamp" %}</th>
            <th scope="col" style="border-bottom: 2px solid black; text-align: left; padding: 0.1em 0.3em;">{% translate "Subject" %}</th>
            <th scope="col" style="border-bottom: 2px solid black; text-align: left; padding: 0.1em 0.3em;">{% translate "From" %}</th>
            <th scope="col" style="border-bottom: 2px solid black; text-align: left; padding: 0.1em 0.3em;">{% translate "To" %}</th>
        </tr>
    </thead>
    <tbody>
    {% for email in mail_list %}
        <tr 
            {% if forloop.counter|divisibleby:2 %}style="background-color: lightgray"{% endif %}
            onclick="window.location='{% url "django_file_inbox:file_inbox_mail" filename=email.filename %}'"
        >
            <td scope="row" style="text-align: left; padding: 0.1em 0.3em;">{{ email.filename }}</td>
            <td style="text-align: left; padding: 0.1em 0.3em;"> {{ email.timestamp }}</td>
            <td style="text-align: left; padding: 0.1em 0.3em;"> {{ email.subject }}</td>
            <td style="text-align: left; padding: 0.1em 0.3em;"> {{ email.from }}</td>
            <td style="text-align: left; padding: 0.1em 0.3em;"> {{ email.to }}</td>
        </tr>
    {% empty %}
    <tr>
        <td class="text-center">{% translate "No messages found" %}</td>
    </tr>
    {% endfor %}
    </tbody>
</table>
{% block inbox_pagination_bottom %}
{% include 'django_file_inbox/_pagination.html' %}
{% endblock inbox_pagination_bottom %}

{% endblock main_block %}

src/django_file_inbox/templates/django_file_inbox/processed/inbox_email.html
{% extends file_inbox_base_template %}
{% load custom_block %}
{% load i18n %}

{% block main_block %}
<br/>
<div style="margin: 0 auto; padding: 10px; border: 1px solid #EF9A9A; border-radius: 4px; overflow: hidden; display: flex; flex-direction: column; width: 75vw;">
    <h3>{{ filename }}</h3>
    <span><hr /></span>
    <span><strong>Subject: </strong>{{ subject }}</span>
    <small>{{ timestamp }}</small>
    <span><hr /></span>
    {{ email_content|linebreaks }}
</div>
{% endblock main_block %}